<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Pages\**" />
    <Compile Remove="Presenters\**" />
    <EmbeddedResource Remove="Pages\**" />
    <EmbeddedResource Remove="Presenters\**" />
    <None Remove="Pages\**" />
    <None Remove="Presenters\**" />
    <Page Remove="Pages\**" />
    <Page Remove="Presenters\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MySql.Data" Version="9.4.0" />
    <ProjectReference Include="..\CommonLib\CommonLib.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
